// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package database

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockTX is an autogenerated mock type for the TX type
type MockTX struct {
	mock.Mock
}

type MockTX_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTX) EXPECT() *MockTX_Expecter {
	return &MockTX_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: query, args
func (_m *MockTX) Exec(query string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (sql.Result, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) sql.Result); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTX_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockTX_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - args ...interface{}
func (_e *MockTX_Expecter) Exec(query interface{}, args ...interface{}) *MockTX_Exec_Call {
	return &MockTX_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockTX_Exec_Call) Run(run func(query string, args ...interface{})) *MockTX_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockTX_Exec_Call) Return(res sql.Result, err error) *MockTX_Exec_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockTX_Exec_Call) RunAndReturn(run func(string, ...interface{}) (sql.Result, error)) *MockTX_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NamedExec provides a mock function with given fields: query, arg
func (_m *MockTX) NamedExec(query string, arg interface{}) (sql.Result, error) {
	ret := _m.Called(query, arg)

	if len(ret) == 0 {
		panic("no return value specified for NamedExec")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(string, interface{}) (sql.Result, error)); ok {
		return rf(query, arg)
	}
	if rf, ok := ret.Get(0).(func(string, interface{}) sql.Result); ok {
		r0 = rf(query, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = rf(query, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTX_NamedExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedExec'
type MockTX_NamedExec_Call struct {
	*mock.Call
}

// NamedExec is a helper method to define mock.On call
//   - query string
//   - arg interface{}
func (_e *MockTX_Expecter) NamedExec(query interface{}, arg interface{}) *MockTX_NamedExec_Call {
	return &MockTX_NamedExec_Call{Call: _e.mock.On("NamedExec", query, arg)}
}

func (_c *MockTX_NamedExec_Call) Run(run func(query string, arg interface{})) *MockTX_NamedExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockTX_NamedExec_Call) Return(res sql.Result, err error) *MockTX_NamedExec_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockTX_NamedExec_Call) RunAndReturn(run func(string, interface{}) (sql.Result, error)) *MockTX_NamedExec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTX creates a new instance of MockTX. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTX(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTX {
	mock := &MockTX{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
