// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package database

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockStats is an autogenerated mock type for the Stats type
type MockStats struct {
	mock.Mock
}

type MockStats_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStats) EXPECT() *MockStats_Expecter {
	return &MockStats_Expecter{mock: &_m.Mock}
}

// Stats provides a mock function with no fields
func (_m *MockStats) Stats() sql.DBStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 sql.DBStats
	if rf, ok := ret.Get(0).(func() sql.DBStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(sql.DBStats)
	}

	return r0
}

// MockStats_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockStats_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockStats_Expecter) Stats() *MockStats_Stats_Call {
	return &MockStats_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockStats_Stats_Call) Run(run func()) *MockStats_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStats_Stats_Call) Return(_a0 sql.DBStats) *MockStats_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStats_Stats_Call) RunAndReturn(run func() sql.DBStats) *MockStats_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStats creates a new instance of MockStats. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStats(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStats {
	mock := &MockStats{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
