// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package log

import (
	log "toll/internal/log"

	mock "github.com/stretchr/testify/mock"
)

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: args
func (_m *MockLogger) Debug(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Debug(args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(args ...interface{})) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(...interface{})) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Debuge provides a mock function with given fields: err, args
func (_m *MockLogger) Debuge(err error, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Debuge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debuge'
type MockLogger_Debuge_Call struct {
	*mock.Call
}

// Debuge is a helper method to define mock.On call
//   - err error
//   - args ...interface{}
func (_e *MockLogger_Expecter) Debuge(err interface{}, args ...interface{}) *MockLogger_Debuge_Call {
	return &MockLogger_Debuge_Call{Call: _e.mock.On("Debuge",
		append([]interface{}{err}, args...)...)}
}

func (_c *MockLogger_Debuge_Call) Run(run func(err error, args ...interface{})) *MockLogger_Debuge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Debuge_Call) Return() *MockLogger_Debuge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debuge_Call) RunAndReturn(run func(error, ...interface{})) *MockLogger_Debuge_Call {
	_c.Run(run)
	return _c
}

// Debugf provides a mock function with given fields: format, args
func (_m *MockLogger) Debugf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type MockLogger_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Debugf(format interface{}, args ...interface{}) *MockLogger_Debugf_Call {
	return &MockLogger_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Debugf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Debugf_Call) Return() *MockLogger_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debugf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Debugf_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: args
func (_m *MockLogger) Error(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Error(args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(args ...interface{})) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(...interface{})) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Errore provides a mock function with given fields: err, args
func (_m *MockLogger) Errore(err error, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Errore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errore'
type MockLogger_Errore_Call struct {
	*mock.Call
}

// Errore is a helper method to define mock.On call
//   - err error
//   - args ...interface{}
func (_e *MockLogger_Expecter) Errore(err interface{}, args ...interface{}) *MockLogger_Errore_Call {
	return &MockLogger_Errore_Call{Call: _e.mock.On("Errore",
		append([]interface{}{err}, args...)...)}
}

func (_c *MockLogger_Errore_Call) Run(run func(err error, args ...interface{})) *MockLogger_Errore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Errore_Call) Return() *MockLogger_Errore_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Errore_Call) RunAndReturn(run func(error, ...interface{})) *MockLogger_Errore_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function with given fields: format, args
func (_m *MockLogger) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type MockLogger_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Errorf(format interface{}, args ...interface{}) *MockLogger_Errorf_Call {
	return &MockLogger_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Errorf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Errorf_Call) Return() *MockLogger_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Errorf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Errorf_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function with given fields: args
func (_m *MockLogger) Fatal(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Fatal(args ...interface{}) *MockLogger_Fatal_Call {
	return &MockLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Fatal_Call) Run(run func(args ...interface{})) *MockLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Fatal_Call) Return() *MockLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatal_Call) RunAndReturn(run func(...interface{})) *MockLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// Fatale provides a mock function with given fields: err, args
func (_m *MockLogger) Fatale(err error, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Fatale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatale'
type MockLogger_Fatale_Call struct {
	*mock.Call
}

// Fatale is a helper method to define mock.On call
//   - err error
//   - args ...interface{}
func (_e *MockLogger_Expecter) Fatale(err interface{}, args ...interface{}) *MockLogger_Fatale_Call {
	return &MockLogger_Fatale_Call{Call: _e.mock.On("Fatale",
		append([]interface{}{err}, args...)...)}
}

func (_c *MockLogger_Fatale_Call) Run(run func(err error, args ...interface{})) *MockLogger_Fatale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Fatale_Call) Return() *MockLogger_Fatale_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatale_Call) RunAndReturn(run func(error, ...interface{})) *MockLogger_Fatale_Call {
	_c.Run(run)
	return _c
}

// Fatalf provides a mock function with given fields: format, args
func (_m *MockLogger) Fatalf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Fatalf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatalf'
type MockLogger_Fatalf_Call struct {
	*mock.Call
}

// Fatalf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Fatalf(format interface{}, args ...interface{}) *MockLogger_Fatalf_Call {
	return &MockLogger_Fatalf_Call{Call: _e.mock.On("Fatalf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Fatalf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Fatalf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Fatalf_Call) Return() *MockLogger_Fatalf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatalf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Fatalf_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function with given fields: args
func (_m *MockLogger) Info(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Info(args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(args ...interface{})) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(...interface{})) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Infoe provides a mock function with given fields: err, args
func (_m *MockLogger) Infoe(err error, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Infoe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infoe'
type MockLogger_Infoe_Call struct {
	*mock.Call
}

// Infoe is a helper method to define mock.On call
//   - err error
//   - args ...interface{}
func (_e *MockLogger_Expecter) Infoe(err interface{}, args ...interface{}) *MockLogger_Infoe_Call {
	return &MockLogger_Infoe_Call{Call: _e.mock.On("Infoe",
		append([]interface{}{err}, args...)...)}
}

func (_c *MockLogger_Infoe_Call) Run(run func(err error, args ...interface{})) *MockLogger_Infoe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Infoe_Call) Return() *MockLogger_Infoe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infoe_Call) RunAndReturn(run func(error, ...interface{})) *MockLogger_Infoe_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function with given fields: format, args
func (_m *MockLogger) Infof(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockLogger_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Infof(format interface{}, args ...interface{}) *MockLogger_Infof_Call {
	return &MockLogger_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Infof_Call) Run(run func(format string, args ...interface{})) *MockLogger_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Infof_Call) Return() *MockLogger_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infof_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Infof_Call {
	_c.Run(run)
	return _c
}

// Panic provides a mock function with given fields: args
func (_m *MockLogger) Panic(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type MockLogger_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Panic(args ...interface{}) *MockLogger_Panic_Call {
	return &MockLogger_Panic_Call{Call: _e.mock.On("Panic",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Panic_Call) Run(run func(args ...interface{})) *MockLogger_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Panic_Call) Return() *MockLogger_Panic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Panic_Call) RunAndReturn(run func(...interface{})) *MockLogger_Panic_Call {
	_c.Run(run)
	return _c
}

// Panice provides a mock function with given fields: err, args
func (_m *MockLogger) Panice(err error, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Panice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panice'
type MockLogger_Panice_Call struct {
	*mock.Call
}

// Panice is a helper method to define mock.On call
//   - err error
//   - args ...interface{}
func (_e *MockLogger_Expecter) Panice(err interface{}, args ...interface{}) *MockLogger_Panice_Call {
	return &MockLogger_Panice_Call{Call: _e.mock.On("Panice",
		append([]interface{}{err}, args...)...)}
}

func (_c *MockLogger_Panice_Call) Run(run func(err error, args ...interface{})) *MockLogger_Panice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Panice_Call) Return() *MockLogger_Panice_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Panice_Call) RunAndReturn(run func(error, ...interface{})) *MockLogger_Panice_Call {
	_c.Run(run)
	return _c
}

// Panicf provides a mock function with given fields: format, args
func (_m *MockLogger) Panicf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Panicf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panicf'
type MockLogger_Panicf_Call struct {
	*mock.Call
}

// Panicf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Panicf(format interface{}, args ...interface{}) *MockLogger_Panicf_Call {
	return &MockLogger_Panicf_Call{Call: _e.mock.On("Panicf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Panicf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Panicf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Panicf_Call) Return() *MockLogger_Panicf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Panicf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Panicf_Call {
	_c.Run(run)
	return _c
}

// Print provides a mock function with given fields: args
func (_m *MockLogger) Print(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type MockLogger_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Print(args ...interface{}) *MockLogger_Print_Call {
	return &MockLogger_Print_Call{Call: _e.mock.On("Print",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Print_Call) Run(run func(args ...interface{})) *MockLogger_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Print_Call) Return() *MockLogger_Print_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Print_Call) RunAndReturn(run func(...interface{})) *MockLogger_Print_Call {
	_c.Run(run)
	return _c
}

// Printe provides a mock function with given fields: err, args
func (_m *MockLogger) Printe(err error, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Printe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printe'
type MockLogger_Printe_Call struct {
	*mock.Call
}

// Printe is a helper method to define mock.On call
//   - err error
//   - args ...interface{}
func (_e *MockLogger_Expecter) Printe(err interface{}, args ...interface{}) *MockLogger_Printe_Call {
	return &MockLogger_Printe_Call{Call: _e.mock.On("Printe",
		append([]interface{}{err}, args...)...)}
}

func (_c *MockLogger_Printe_Call) Run(run func(err error, args ...interface{})) *MockLogger_Printe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Printe_Call) Return() *MockLogger_Printe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Printe_Call) RunAndReturn(run func(error, ...interface{})) *MockLogger_Printe_Call {
	_c.Run(run)
	return _c
}

// Printf provides a mock function with given fields: format, args
func (_m *MockLogger) Printf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type MockLogger_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Printf(format interface{}, args ...interface{}) *MockLogger_Printf_Call {
	return &MockLogger_Printf_Call{Call: _e.mock.On("Printf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Printf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Printf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Printf_Call) Return() *MockLogger_Printf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Printf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Printf_Call {
	_c.Run(run)
	return _c
}

// Trace provides a mock function with given fields: args
func (_m *MockLogger) Trace(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Trace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trace'
type MockLogger_Trace_Call struct {
	*mock.Call
}

// Trace is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Trace(args ...interface{}) *MockLogger_Trace_Call {
	return &MockLogger_Trace_Call{Call: _e.mock.On("Trace",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Trace_Call) Run(run func(args ...interface{})) *MockLogger_Trace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Trace_Call) Return() *MockLogger_Trace_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Trace_Call) RunAndReturn(run func(...interface{})) *MockLogger_Trace_Call {
	_c.Run(run)
	return _c
}

// Tracee provides a mock function with given fields: err, args
func (_m *MockLogger) Tracee(err error, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Tracee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tracee'
type MockLogger_Tracee_Call struct {
	*mock.Call
}

// Tracee is a helper method to define mock.On call
//   - err error
//   - args ...interface{}
func (_e *MockLogger_Expecter) Tracee(err interface{}, args ...interface{}) *MockLogger_Tracee_Call {
	return &MockLogger_Tracee_Call{Call: _e.mock.On("Tracee",
		append([]interface{}{err}, args...)...)}
}

func (_c *MockLogger_Tracee_Call) Run(run func(err error, args ...interface{})) *MockLogger_Tracee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Tracee_Call) Return() *MockLogger_Tracee_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Tracee_Call) RunAndReturn(run func(error, ...interface{})) *MockLogger_Tracee_Call {
	_c.Run(run)
	return _c
}

// Tracef provides a mock function with given fields: format, args
func (_m *MockLogger) Tracef(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Tracef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tracef'
type MockLogger_Tracef_Call struct {
	*mock.Call
}

// Tracef is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Tracef(format interface{}, args ...interface{}) *MockLogger_Tracef_Call {
	return &MockLogger_Tracef_Call{Call: _e.mock.On("Tracef",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Tracef_Call) Run(run func(format string, args ...interface{})) *MockLogger_Tracef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Tracef_Call) Return() *MockLogger_Tracef_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Tracef_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Tracef_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function with given fields: args
func (_m *MockLogger) Warn(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockLogger_Expecter) Warn(args ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(args ...interface{})) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(...interface{})) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// Warne provides a mock function with given fields: err, args
func (_m *MockLogger) Warne(err error, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Warne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warne'
type MockLogger_Warne_Call struct {
	*mock.Call
}

// Warne is a helper method to define mock.On call
//   - err error
//   - args ...interface{}
func (_e *MockLogger_Expecter) Warne(err interface{}, args ...interface{}) *MockLogger_Warne_Call {
	return &MockLogger_Warne_Call{Call: _e.mock.On("Warne",
		append([]interface{}{err}, args...)...)}
}

func (_c *MockLogger_Warne_Call) Run(run func(err error, args ...interface{})) *MockLogger_Warne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warne_Call) Return() *MockLogger_Warne_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warne_Call) RunAndReturn(run func(error, ...interface{})) *MockLogger_Warne_Call {
	_c.Run(run)
	return _c
}

// Warnf provides a mock function with given fields: format, args
func (_m *MockLogger) Warnf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// MockLogger_Warnf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnf'
type MockLogger_Warnf_Call struct {
	*mock.Call
}

// Warnf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Warnf(format interface{}, args ...interface{}) *MockLogger_Warnf_Call {
	return &MockLogger_Warnf_Call{Call: _e.mock.On("Warnf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Warnf_Call) Run(run func(format string, args ...interface{})) *MockLogger_Warnf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warnf_Call) Return() *MockLogger_Warnf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warnf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogger_Warnf_Call {
	_c.Run(run)
	return _c
}

// WithField provides a mock function with given fields: key, val
func (_m *MockLogger) WithField(key string, val interface{}) log.Logger {
	ret := _m.Called(key, val)

	if len(ret) == 0 {
		panic("no return value specified for WithField")
	}

	var r0 log.Logger
	if rf, ok := ret.Get(0).(func(string, interface{}) log.Logger); ok {
		r0 = rf(key, val)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Logger)
		}
	}

	return r0
}

// MockLogger_WithField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithField'
type MockLogger_WithField_Call struct {
	*mock.Call
}

// WithField is a helper method to define mock.On call
//   - key string
//   - val interface{}
func (_e *MockLogger_Expecter) WithField(key interface{}, val interface{}) *MockLogger_WithField_Call {
	return &MockLogger_WithField_Call{Call: _e.mock.On("WithField", key, val)}
}

func (_c *MockLogger_WithField_Call) Run(run func(key string, val interface{})) *MockLogger_WithField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockLogger_WithField_Call) Return(_a0 log.Logger) *MockLogger_WithField_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogger_WithField_Call) RunAndReturn(run func(string, interface{}) log.Logger) *MockLogger_WithField_Call {
	_c.Call.Return(run)
	return _c
}

// WithFields provides a mock function with given fields: fields
func (_m *MockLogger) WithFields(fields log.Fields) log.Logger {
	ret := _m.Called(fields)

	if len(ret) == 0 {
		panic("no return value specified for WithFields")
	}

	var r0 log.Logger
	if rf, ok := ret.Get(0).(func(log.Fields) log.Logger); ok {
		r0 = rf(fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log.Logger)
		}
	}

	return r0
}

// MockLogger_WithFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithFields'
type MockLogger_WithFields_Call struct {
	*mock.Call
}

// WithFields is a helper method to define mock.On call
//   - fields log.Fields
func (_e *MockLogger_Expecter) WithFields(fields interface{}) *MockLogger_WithFields_Call {
	return &MockLogger_WithFields_Call{Call: _e.mock.On("WithFields", fields)}
}

func (_c *MockLogger_WithFields_Call) Run(run func(fields log.Fields)) *MockLogger_WithFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(log.Fields))
	})
	return _c
}

func (_c *MockLogger_WithFields_Call) Return(_a0 log.Logger) *MockLogger_WithFields_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogger_WithFields_Call) RunAndReturn(run func(log.Fields) log.Logger) *MockLogger_WithFields_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
