// Code generated by ogen, DO NOT EDIT.

package restapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Health implements Health operation.
//
// Returns OK.
//
// GET /health
func (UnimplementedHandler) Health(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// RecordTollEvent implements RecordTollEvent operation.
//
// Stores toll event log to event database.
//
// POST /toll-events
func (UnimplementedHandler) RecordTollEvent(ctx context.Context, req *TollEvent) (r RecordTollEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemStatusCode) {
	r = new(ProblemStatusCode)
	return r
}
