// Code generated by ogen, DO NOT EDIT.

package restapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Health implements Health operation.
	//
	// Returns OK.
	//
	// GET /health
	Health(ctx context.Context) error
	// RecordTollEvent implements RecordTollEvent operation.
	//
	// Stores toll event log to event database.
	//
	// POST /toll-events
	RecordTollEvent(ctx context.Context, req *TollEvent) (RecordTollEventRes, error)
	// NewError creates *ProblemStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
