// Code generated by ogen, DO NOT EDIT.

package restapi

// OperationName is the ogen operation name
type OperationName = string

const (
	HealthOperation          OperationName = "Health"
	RecordTollEventOperation OperationName = "RecordTollEvent"
)
