// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package auth

import (
	context "context"
	restapi "toll/api/restapi"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthorization is an autogenerated mock type for the Authorization type
type MockAuthorization struct {
	mock.Mock
}

type MockAuthorization_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorization) EXPECT() *MockAuthorization_Expecter {
	return &MockAuthorization_Expecter{mock: &_m.Mock}
}

// HandleApiKeyAuth provides a mock function with given fields: ctx, operationName, t
func (_m *MockAuthorization) HandleApiKeyAuth(ctx context.Context, operationName string, t restapi.ApiKeyAuth) (context.Context, error) {
	ret := _m.Called(ctx, operationName, t)

	if len(ret) == 0 {
		panic("no return value specified for HandleApiKeyAuth")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, restapi.ApiKeyAuth) (context.Context, error)); ok {
		return rf(ctx, operationName, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, restapi.ApiKeyAuth) context.Context); ok {
		r0 = rf(ctx, operationName, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, restapi.ApiKeyAuth) error); ok {
		r1 = rf(ctx, operationName, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorization_HandleApiKeyAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleApiKeyAuth'
type MockAuthorization_HandleApiKeyAuth_Call struct {
	*mock.Call
}

// HandleApiKeyAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - operationName string
//   - t restapi.ApiKeyAuth
func (_e *MockAuthorization_Expecter) HandleApiKeyAuth(ctx interface{}, operationName interface{}, t interface{}) *MockAuthorization_HandleApiKeyAuth_Call {
	return &MockAuthorization_HandleApiKeyAuth_Call{Call: _e.mock.On("HandleApiKeyAuth", ctx, operationName, t)}
}

func (_c *MockAuthorization_HandleApiKeyAuth_Call) Run(run func(ctx context.Context, operationName string, t restapi.ApiKeyAuth)) *MockAuthorization_HandleApiKeyAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(restapi.ApiKeyAuth))
	})
	return _c
}

func (_c *MockAuthorization_HandleApiKeyAuth_Call) Return(_a0 context.Context, _a1 error) *MockAuthorization_HandleApiKeyAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorization_HandleApiKeyAuth_Call) RunAndReturn(run func(context.Context, string, restapi.ApiKeyAuth) (context.Context, error)) *MockAuthorization_HandleApiKeyAuth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorization creates a new instance of MockAuthorization. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorization(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorization {
	mock := &MockAuthorization{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
