version: 2

run:
  concurrency: 4
  timeout: 5m
  tests: true
  build-tags:
    - mock
  modules-download-mode: vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ''
  sort-results: false

linters:
  enable:
    - bodyclose
    - misspell
    - gosec
    - godot
    - godox
    - tparallel
    - noctx
    - asciicheck
    - prealloc
    - gocyclo
    - errorlint
    - nlreturn
    - whitespace
    - wsl
    - unconvert
    - predeclared
    - paralleltest

formatter:
  enable:
    - gci
    - gofmt

formatter-settings:
  gci:
    sections:
      - Standard
      - Default
      - prefix(toll/api)
      - prefix(toll)
      - prefix(toll/internal)
    custom-order: true

linters-settings:
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
