// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package audit

import (
	context "context"
	audit "toll/api/audit"

	mock "github.com/stretchr/testify/mock"
)

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Log provides a mock function with given fields: ctx, method
func (_m *MockLogger) Log(ctx context.Context, method string) {
	_m.Called(ctx, method)
}

// MockLogger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockLogger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
func (_e *MockLogger_Expecter) Log(ctx interface{}, method interface{}) *MockLogger_Log_Call {
	return &MockLogger_Log_Call{Call: _e.mock.On("Log", ctx, method)}
}

func (_c *MockLogger_Log_Call) Run(run func(ctx context.Context, method string)) *MockLogger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLogger_Log_Call) Return() *MockLogger_Log_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Log_Call) RunAndReturn(run func(context.Context, string)) *MockLogger_Log_Call {
	_c.Run(run)
	return _c
}

// LogP provides a mock function with given fields: ctx, method, params
func (_m *MockLogger) LogP(ctx context.Context, method string, params audit.Parameters) {
	_m.Called(ctx, method, params)
}

// MockLogger_LogP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogP'
type MockLogger_LogP_Call struct {
	*mock.Call
}

// LogP is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - params audit.Parameters
func (_e *MockLogger_Expecter) LogP(ctx interface{}, method interface{}, params interface{}) *MockLogger_LogP_Call {
	return &MockLogger_LogP_Call{Call: _e.mock.On("LogP", ctx, method, params)}
}

func (_c *MockLogger_LogP_Call) Run(run func(ctx context.Context, method string, params audit.Parameters)) *MockLogger_LogP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(audit.Parameters))
	})
	return _c
}

func (_c *MockLogger_LogP_Call) Return() *MockLogger_LogP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_LogP_Call) RunAndReturn(run func(context.Context, string, audit.Parameters)) *MockLogger_LogP_Call {
	_c.Run(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
