// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "toll/api/types"
)

// MockApiKeyRepository is an autogenerated mock type for the ApiKeyRepository type
type MockApiKeyRepository struct {
	mock.Mock
}

type MockApiKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApiKeyRepository) EXPECT() *MockApiKeyRepository_Expecter {
	return &MockApiKeyRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, keyHash
func (_m *MockApiKeyRepository) Get(ctx context.Context, keyHash string) (*types.ApiKey, error) {
	ret := _m.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*types.ApiKey, error)); ok {
		return rf(ctx, keyHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *types.ApiKey); ok {
		r0 = rf(ctx, keyHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ApiKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApiKeyRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockApiKeyRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - keyHash string
func (_e *MockApiKeyRepository_Expecter) Get(ctx interface{}, keyHash interface{}) *MockApiKeyRepository_Get_Call {
	return &MockApiKeyRepository_Get_Call{Call: _e.mock.On("Get", ctx, keyHash)}
}

func (_c *MockApiKeyRepository_Get_Call) Run(run func(ctx context.Context, keyHash string)) *MockApiKeyRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockApiKeyRepository_Get_Call) Return(_a0 *types.ApiKey, _a1 error) *MockApiKeyRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApiKeyRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*types.ApiKey, error)) *MockApiKeyRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApiKeyRepository creates a new instance of MockApiKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApiKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApiKeyRepository {
	mock := &MockApiKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
