// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	types "toll/api/types"
)

// MockTollEventRepository is an autogenerated mock type for the TollEventRepository type
type MockTollEventRepository struct {
	mock.Mock
}

type MockTollEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTollEventRepository) EXPECT() *MockTollEventRepository_Expecter {
	return &MockTollEventRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx, license, t
func (_m *MockTollEventRepository) GetAll(ctx context.Context, license string, t time.Time) ([]*types.TollEvent, error) {
	ret := _m.Called(ctx, license, t)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*types.TollEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*types.TollEvent, error)); ok {
		return rf(ctx, license, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*types.TollEvent); ok {
		r0 = rf(ctx, license, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.TollEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, license, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTollEventRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTollEventRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - license string
//   - t time.Time
func (_e *MockTollEventRepository_Expecter) GetAll(ctx interface{}, license interface{}, t interface{}) *MockTollEventRepository_GetAll_Call {
	return &MockTollEventRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, license, t)}
}

func (_c *MockTollEventRepository_GetAll_Call) Run(run func(ctx context.Context, license string, t time.Time)) *MockTollEventRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockTollEventRepository_GetAll_Call) Return(_a0 []*types.TollEvent, _a1 error) *MockTollEventRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTollEventRepository_GetAll_Call) RunAndReturn(run func(context.Context, string, time.Time) ([]*types.TollEvent, error)) *MockTollEventRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function with given fields: ctx, event
func (_m *MockTollEventRepository) Record(ctx context.Context, event *types.TollEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.TollEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTollEventRepository_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockTollEventRepository_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - event *types.TollEvent
func (_e *MockTollEventRepository_Expecter) Record(ctx interface{}, event interface{}) *MockTollEventRepository_Record_Call {
	return &MockTollEventRepository_Record_Call{Call: _e.mock.On("Record", ctx, event)}
}

func (_c *MockTollEventRepository_Record_Call) Run(run func(ctx context.Context, event *types.TollEvent)) *MockTollEventRepository_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.TollEvent))
	})
	return _c
}

func (_c *MockTollEventRepository_Record_Call) Return(_a0 error) *MockTollEventRepository_Record_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTollEventRepository_Record_Call) RunAndReturn(run func(context.Context, *types.TollEvent) error) *MockTollEventRepository_Record_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDailyFee provides a mock function with given fields: ctx, dailyFee
func (_m *MockTollEventRepository) UpdateDailyFee(ctx context.Context, dailyFee types.DailyFee) error {
	ret := _m.Called(ctx, dailyFee)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDailyFee")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.DailyFee) error); ok {
		r0 = rf(ctx, dailyFee)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTollEventRepository_UpdateDailyFee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDailyFee'
type MockTollEventRepository_UpdateDailyFee_Call struct {
	*mock.Call
}

// UpdateDailyFee is a helper method to define mock.On call
//   - ctx context.Context
//   - dailyFee types.DailyFee
func (_e *MockTollEventRepository_Expecter) UpdateDailyFee(ctx interface{}, dailyFee interface{}) *MockTollEventRepository_UpdateDailyFee_Call {
	return &MockTollEventRepository_UpdateDailyFee_Call{Call: _e.mock.On("UpdateDailyFee", ctx, dailyFee)}
}

func (_c *MockTollEventRepository_UpdateDailyFee_Call) Run(run func(ctx context.Context, dailyFee types.DailyFee)) *MockTollEventRepository_UpdateDailyFee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.DailyFee))
	})
	return _c
}

func (_c *MockTollEventRepository_UpdateDailyFee_Call) Return(_a0 error) *MockTollEventRepository_UpdateDailyFee_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTollEventRepository_UpdateDailyFee_Call) RunAndReturn(run func(context.Context, types.DailyFee) error) *MockTollEventRepository_UpdateDailyFee_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTollEventRepository creates a new instance of MockTollEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTollEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTollEventRepository {
	mock := &MockTollEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
