// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// ValidateApiKey provides a mock function with given fields: ctx, key
func (_m *MockAuthService) ValidateApiKey(ctx context.Context, key string) (*uuid.UUID, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ValidateApiKey")
	}

	var r0 *uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*uuid.UUID, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *uuid.UUID); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_ValidateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateApiKey'
type MockAuthService_ValidateApiKey_Call struct {
	*mock.Call
}

// ValidateApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAuthService_Expecter) ValidateApiKey(ctx interface{}, key interface{}) *MockAuthService_ValidateApiKey_Call {
	return &MockAuthService_ValidateApiKey_Call{Call: _e.mock.On("ValidateApiKey", ctx, key)}
}

func (_c *MockAuthService_ValidateApiKey_Call) Run(run func(ctx context.Context, key string)) *MockAuthService_ValidateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_ValidateApiKey_Call) Return(_a0 *uuid.UUID, _a1 error) *MockAuthService_ValidateApiKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_ValidateApiKey_Call) RunAndReturn(run func(context.Context, string) (*uuid.UUID, error)) *MockAuthService_ValidateApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
