// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockBillingService is an autogenerated mock type for the BillingService type
type MockBillingService struct {
	mock.Mock
}

type MockBillingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillingService) EXPECT() *MockBillingService_Expecter {
	return &MockBillingService_Expecter{mock: &_m.Mock}
}

// TriggerFor provides a mock function with given fields: license
func (_m *MockBillingService) TriggerFor(license string) {
	_m.Called(license)
}

// MockBillingService_TriggerFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerFor'
type MockBillingService_TriggerFor_Call struct {
	*mock.Call
}

// TriggerFor is a helper method to define mock.On call
//   - license string
func (_e *MockBillingService_Expecter) TriggerFor(license interface{}) *MockBillingService_TriggerFor_Call {
	return &MockBillingService_TriggerFor_Call{Call: _e.mock.On("TriggerFor", license)}
}

func (_c *MockBillingService_TriggerFor_Call) Run(run func(license string)) *MockBillingService_TriggerFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBillingService_TriggerFor_Call) Return() *MockBillingService_TriggerFor_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBillingService_TriggerFor_Call) RunAndReturn(run func(string)) *MockBillingService_TriggerFor_Call {
	_c.Run(run)
	return _c
}

// NewMockBillingService creates a new instance of MockBillingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillingService {
	mock := &MockBillingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
