// go:build mock

// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "toll/api/types"
)

// MockTollEventService is an autogenerated mock type for the TollEventService type
type MockTollEventService struct {
	mock.Mock
}

type MockTollEventService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTollEventService) EXPECT() *MockTollEventService_Expecter {
	return &MockTollEventService_Expecter{mock: &_m.Mock}
}

// Record provides a mock function with given fields: ctx, event
func (_m *MockTollEventService) Record(ctx context.Context, event *types.TollEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.TollEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTollEventService_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockTollEventService_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - ctx context.Context
//   - event *types.TollEvent
func (_e *MockTollEventService_Expecter) Record(ctx interface{}, event interface{}) *MockTollEventService_Record_Call {
	return &MockTollEventService_Record_Call{Call: _e.mock.On("Record", ctx, event)}
}

func (_c *MockTollEventService_Record_Call) Run(run func(ctx context.Context, event *types.TollEvent)) *MockTollEventService_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.TollEvent))
	})
	return _c
}

func (_c *MockTollEventService_Record_Call) Return(_a0 error) *MockTollEventService_Record_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTollEventService_Record_Call) RunAndReturn(run func(context.Context, *types.TollEvent) error) *MockTollEventService_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTollEventService creates a new instance of MockTollEventService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTollEventService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTollEventService {
	mock := &MockTollEventService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
